#pragma once
#ifdef TEST_REAL_AGENT_CONFIG
#include TEST_REAL_AGENT_CONFIG_PATH
#else
#define AGENT_CHAN_VOICE "voice"
#define AGENT_CHAN_SYSTEM "system"
#define AGENT_CHAN_FEISHU "feishu"
#define AGENT_AUDIO_CAPTURE_DEV "capture"
#define AGENT_AUDIO_PLAYBACK_DEV "playback"
#define AGENT_ASR_CHUNK_SIZE 3200
#define AGENT_VOICE_SAMPLE_RATE 16000
#define AGENT_VOICE_CHANNELS 1
#define AGENT_VOICE_BITS 16
#define AGENT_VOICE_MAX_RECORD_MS 10000
#define AGENT_VOICE_PCM_BUF_SIZE 320000
#define AGENT_VOICE_STACK (256 * 1024)
#define AGENT_TTS_WS_SAMPLE_RATE 24000
#define AGENT_VOICE_PRIO 50
#define AGENT_CRON_MAX_JOBS 16
#define AGENT_CRON_ID_LEN 9
#define AGENT_CRON_FILE "cron-fixture.json"
#define AGENT_CRON_FILE_MAX_SIZE (64 * 1024)
#define AGENT_CRON_CHECK_INTERVAL_MS 1000
#define AGENT_CRON_STACK (256 * 1024)
#define AGENT_CRON_PRIO 50
#endif
