############################################################################
# Contest 2026 team 120 study terminal - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = study_terminal
PRIORITY  = $(CONFIG_LVX_USE_DEMO_CONTEST2026_120_STUDY_TERMINAL_PRIORITY)
STACKSIZE = $(CONFIG_LVX_USE_DEMO_CONTEST2026_120_STUDY_TERMINAL_STACKSIZE)
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_120_STUDY_TERMINAL)

MAINSRC = study_terminal_main.c

include $(APPDIR)/Application.mk
